# Generated by Django 4.2.3 on 2023-07-18 23:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0005_sample_dna_alter_sample_related"),
    ]

    operations = [
        migrations.AddField(
            model_name="sample",
            name="sequence",
            field=models.TextField(blank=True, null=True),
        ),
    ]
