# Generated by Django 4.2.3 on 2023-07-18 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0006_sample_sequence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='dna',
        ),
    ]
