# Generated by Django 4.2.3 on 2023-07-19 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0007_remove_sample_dna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_sample', to='registry.sample'),
        ),
    ]
