# Generated by Django 4.2.3 on 2023-07-16 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
