# Generated by Django 4.2.3 on 2023-07-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entity", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schema",
            name="digits",
            field=models.IntegerField(verbose_name="ID Digits"),
        ),
    ]
