# Generated by Django 4.2.3 on 2023-07-16 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_container_contents'),
        ('entity', '0002_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='containers',
            field=models.ManyToManyField(blank=True, null=True, to='inventory.container'),
        ),
    ]
