# Generated by Django 4.2.3 on 2023-07-16 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_container_contents'),
        ('entity', '0003_sample_containers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='containers',
            field=models.ManyToManyField(blank=True, to='inventory.container'),
        ),
    ]
