# Generated by Django 4.2.3 on 2023-07-16 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0004_alter_sample_containers'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
