# Generated by Django 4.2.3 on 2023-07-17 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='digits',
        ),
    ]
