# Generated by Django 4.2.3 on 2023-07-17 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_field_type_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registry.sample'),
        ),
    ]
