# Generated by Django 4.2.3 on 2023-07-17 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_sample_related'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='dna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dna_related', to='registry.sample', verbose_name='DNA'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_related', to='registry.sample'),
        ),
    ]
