# Generated by Django 4.2.3 on 2023-07-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eln', '0004_alter_entry_options_alter_entry_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Last modified at'),
        ),
    ]
