# Generated by Django 4.2.3 on 2023-07-16 03:51

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_container'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='location',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.location'),
        ),
    ]
