# Generated by Django 4.2.3 on 2023-07-16 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0002_type_name'),
        ('inventory', '0005_alter_container_location_alter_location_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='contents',
            field=models.ManyToManyField(blank=True, null=True, to='entity.sample'),
        ),
    ]
