# Generated by Django 4.2.3 on 2023-07-16 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0004_alter_sample_containers'),
        ('inventory', '0006_container_contents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='contents',
            field=models.ManyToManyField(blank=True, to='entity.sample'),
        ),
    ]
